version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - ./symfony:/var/www/html
    ports:
      - "80:8000"
    working_dir: /var/www/html
    command: bash -c "if [ ! -f composer.json ]; then symfony new . --webapp --no-interaction; fi && symfony server:start --allow-http --no-tls --port=8000 --listen-ip=0.0.0.0"


  mysql:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
